name: 'ZJU-nCov-Hitcarder Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME1
            password: ZJU_PASSWORD1
            dingtalk_token: DINGTALK_TOKEN1
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            dingtalk_token: DINGTALK_TOKEN2
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
          - username: ZJU_USERNAME4
            password: ZJU_PASSWORD4
          - username: ZJU_USERNAME5
            password: ZJU_PASSWORD5
          - username: ZJU_USERNAME6
            password: ZJU_PASSWORD6
    steps:
      - name: Working
        uses: koala189/AutoHitCarder
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
          pushplus_token: ${{ secrets[matrix.pushplus_token] }}
          serverchan_key: ${{ secrets[matrix.serverchan_key] }}
