name: 'ZJU-nCov-Hitcarder Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
#           - username: ZJU_USERNAME
#             password: ZJU_PASSWORD
#             dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME1
            password: ZJU_PASSWORD1
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
          - username: ZJU_USERNAME4
            password: ZJU_PASSWORD4
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Working
        uses: koala189/AutoHitCarder@main
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
          pushplus_token: ${{ secrets[matrix.pushplus_token] }}
          serverchan_key: ${{ secrets[matrix.serverchan_key] }}
